version: '3.8'

services:
    mongodb:
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb-data:/data/db
    rabbitmq:
      image: rabbitmq
      ports:
      - '5672:5672'
volumes:
  mongodb-data: 